#if !defined(MATERIAL_IDS_GLSL)
#define MATERIAL_IDS_GLSL
// This file was automatically generated by block_wrangler

#ifndef DISTANT_HORIZONS
    #define DH_BLOCK_UNKNOWN -1
    #define DH_BLOCK_LEAVES -1
    #define DH_BLOCK_STONE -1
    #define DH_BLOCK_WOOD -1
    #define DH_BLOCK_METAL -1
    #define DH_BLOCK_DIRT -1
    #define DH_BLOCK_GRASS -1
    #define DH_BLOCK_LAVA -1
    #define DH_BLOCK_DEEPSLATE -1
    #define DH_BLOCK_SNOW -1
    #define DH_BLOCK_SAND -1
    #define DH_BLOCK_TERRACOTTA -1
    #define DH_BLOCK_NETHER_STONE -1
    #define DH_BLOCK_WATER -1
    #define DH_BLOCK_AIR -1
    #define DH_BLOCK_ILLUMINATED -1
#endif


bool isWater(int id) {
    return id == 1001 || id == DH_BLOCK_WATER;
}


bool isIce(int id) {
    return id == 1002;
}


bool isLava(int id) {
    return id == 1022 || id == DH_BLOCK_LAVA;
}


bool isPlant(int id) {
    return id == 1003 || id == 1004 || id == 1005 || id == 1006 || id == 1008 || id == 1009 || id == 1012 || id == 1024 || id == 1025 || id == 1026;
}


bool isLeaves(int id) {
    return id == 1009 || id == DH_BLOCK_LEAVES;
}


struct SwayValues {
	int NONE;
	int UPPER;
	int LOWER;
	int SHORT;
	int HANGING;
	int FLOATING;
	int FULL;
};
const SwayValues Sway = SwayValues(0, 1, 2, 3, 4, 5, 6);
int sway(int id) {
    if (id == 1004) {
        return Sway.UPPER;
    } else if (id == 1005) {
        return Sway.LOWER;
    } else if (id == 1006 || id == 1025) {
        return Sway.SHORT;
    } else if (id == 1007 || id == 1008 || id == 1014 || id == 1016) {
        return Sway.HANGING;
    } else if (id == 1009) {
        return Sway.FULL;
    } else if (id == 1026) {
        return Sway.FLOATING;
    } else {
        return Sway.NONE;
    }
}


bool isTintedGlass(int id) {
    return id == 1010;
}


bool isFireLightColor(int id) {
    return id == 1011 || id == 1012 || id == 1022 || id == 1027;
}


bool isTorchLightColor(int id) {
    return id == 1013 || id == 1014;
}


bool isSoulFireLightColor(int id) {
    return id == 1015 || id == 1016 || id == 1028;
}


bool isRedstoneLightColor(int id) {
    return id == 1017;
}


bool isPurpleFroglight(int id) {
    return id == 1018;
}


bool isYellowFroglight(int id) {
    return id == 1019;
}


bool isGreenFroglight(int id) {
    return id == 1020;
}


bool isMaxEmission(int id) {
    return id == 1021 || id == 1022;
}


bool isLetsLightThrough(int id) {
    return id == 1023 || id == 1024 || id == 1025 || id == 1026 || id == 1027 || id == 1028;
}


bool isEndPortal(int id) {
    return id == 1029;
}


#endif // MATERIAL_IDS_GLSL