#if !defined(MATERIAL_IDS_GLSL)
#define MATERIAL_IDS_GLSL
// This file was automatically generated by block_wrangler

#ifndef DISTANT_HORIZONS
    #define DH_BLOCK_UNKNOWN -1
    #define DH_BLOCK_LEAVES -1
    #define DH_BLOCK_STONE -1
    #define DH_BLOCK_WOOD -1
    #define DH_BLOCK_METAL -1
    #define DH_BLOCK_DIRT -1
    #define DH_BLOCK_GRASS -1
    #define DH_BLOCK_LAVA -1
    #define DH_BLOCK_DEEPSLATE -1
    #define DH_BLOCK_SNOW -1
    #define DH_BLOCK_SAND -1
    #define DH_BLOCK_TERRACOTTA -1
    #define DH_BLOCK_NETHER_STONE -1
    #define DH_BLOCK_WATER -1
    #define DH_BLOCK_AIR -1
    #define DH_BLOCK_ILLUMINATED -1
#endif


bool isWater(int id) {
    return id == 1001 || id == DH_BLOCK_WATER;
}


bool isIce(int id) {
    return id == 1002;
}


bool isLava(int id) {
    return id == 1014 || id == DH_BLOCK_LAVA;
}


bool isPlant(int id) {
    return id == 1003 || id == 1004 || id == 1006 || id == 1016 || id == 1020 || id == 1022 || id == 1024 || id == 1026 || id == 1028 || id == 1030;
}


bool isLeaves(int id) {
    return id == 1004 || id == DH_BLOCK_LEAVES;
}


bool isTintedGlass(int id) {
    return id == 1005;
}


bool isFireLightColor(int id) {
    return id == 1006 || id == 1014 || id == 1017 || id == 1033;
}


bool isTorchLightColor(int id) {
    return id == 1007 || id == 1031;
}


bool isSoulFireLightColor(int id) {
    return id == 1008 || id == 1018 || id == 1032;
}


bool isRedstoneLightColor(int id) {
    return id == 1009;
}


bool isPurpleFroglight(int id) {
    return id == 1010;
}


bool isYellowFroglight(int id) {
    return id == 1011;
}


bool isGreenFroglight(int id) {
    return id == 1012;
}


bool isMaxEmission(int id) {
    return id == 1013 || id == 1014;
}


bool isLetsLightThrough(int id) {
    return id == 1015 || id == 1016 || id == 1017 || id == 1018 || id == 1023 || id == 1027;
}


bool isEndPortal(int id) {
    return id == 1019;
}


bool isGrass(int id) {
    return id == 1020 || id == 1024 || id == 1028;
}


bool isTopHalf(int id) {
    return id == 1021 || id == 1022 || id == 1023 || id == 1024;
}


bool isBottomHalf(int id) {
    return id == 1025 || id == 1026 || id == 1027 || id == 1028;
}


bool isHanging(int id) {
    return id == 1029 || id == 1030 || id == 1031 || id == 1032;
}


bool isFire(int id) {
    return id == 1033;
}


#endif // MATERIAL_IDS_GLSL