#define DEBUG_ENABLE

#define BLOOM_RADIUS 1.0

#define PCSS_SEARCH_SAMPLES 8
#define PCSS_SEARCH_RADIUS 0.5
#define PCSS_MAX_RADIUS 2.0
#define PCSS_MIN_RADIUS 0.0
#define SHADOW_PCF_SAMPLES 8

#define SMOOTH_SSR_STEPS 16
#define ROUGH_SSR_STEPS 8
#define ROUGH_SSR_SAMPLES 4
#define ROUGH_SSR_THRESHOLD 0.5

#define RSM_SAMPLES 16
#define RSM_RADIUS 2.0

#define EMISSIVE_STRENGTH 500.0